### ISSUE TITLE
Markdown output broken by default?

### ISSUE THREAD

**Issue by mpern** [raml2html/markdown-theme#1]
I have installed the theme via`npm install -g raml2html-markdown-theme` and tried it with following minimal file:

    #%RAML 1.0
    title: Internal
    baseUri: https://some-url/
    version: v1
    mediaType: application/json
    protocols:
      - HTTP
      - HTTPS
      
    /asdf:
      post:
        queryString:
          properties:
            test: number

Running
`raml2html --theme raml2html-markdown-theme internal-api.raml > test.md`

Produces following output (yes, all in one line):

    # Internal API documentation version v1 https://some-url/ --- ## /asdf ### /asdf * **post**:

What am I missing?

**Comment by kevinrenskers** [comment]
When I run this I get this, not on one line:

```
# Internal API documentation version v1
https://some-url/

---

## /asdf

### /asdf

* **post**:
```

**Comment by kevinrenskers** [comment]
Are you on Windows maybe?

**Comment by mpern** [comment]
Nope, I am on a Mac. I have tried reinstalling `raml2html` and `raml2html-markdown-theme` but nothing changed.

I will try it on another machine...

**Comment by kevinrenskers** [comment]
Hey @nickwb could you please test this issue for me? I can't reproduce :(

**Comment by nickwb** [comment]
Well the markdown template has unix line endings, so depending on what editor you're using on the Mac, it might appear as one line.

All that said, the markdown template is missing much of the information which is in the deafult html template - including queryString parameters.

**Comment by derlin** [comment]
I have the same problem and I am on Mac. Using the command-line or Sublime Text setup with Unix line endings doesn't help.

**Comment by kevinrenskers** [comment]
Yep, the template is very basic and was never meant to show all possible assets of a RAML file. It might need more info to be useful, I'll leave that up to other people. As for the single line problem, I can't reproduce this, so a PR with a fix would be welcome.

**Comment by kevinrenskers** [comment]
I was able to reproduce the problem when using raml2html as a CLI with a globally installed markdown theme. In other words, like everybody uses it basically, instead of running the examples from within this repo. Weird. I'll look into it, but my guess is that is has something to do with how the package is downloaded from NPM.

**Comment by kevinrenskers** [comment]
Fixed! The problem was that the raml2html-markdown-theme package didn't depend on the nunjucks dependency, and thus that `require` failed, causing raml2html to fall back to default processing behavior, which included minifying the output.

1.0.1 fixes this. Alternatively `npm i -g nunjucks@2.5.x` will also fix the problem :)

**Comment by marcschroeder** [comment]
Sorry to disapoint you, but i still can not get it to work, it workes fine with the theme, but when using it as template (markdown\index.nunjucks) I still get only a oneline markdown. I installed nunjucks, global and local, but I can´t get it to work. Is there something I don´t get or do wrong?

**Comment by kevinrenskers** [comment]
You can't really use it with just a template because then the default processing code is run, which includes minifying. So you'll have to create your own theme ala this markdown theme or use raml2html as a library from node and supply your own config.

**Comment by marcschroeder** [comment]
Right, but that is what I do, I use raml2html -t markdown\index.nunjucks input.raml > output.md and it workes fine, but everything is in one line, is there a spacial character to get a new line?

**Comment by kevinrenskers** [comment]
Yeah that is exactly what doesn't work. Like I said, you can't use it with a template (the -t option), because then raml2html uses the default processing function which minifies the output. You need to either clone the markdown theme, modify it and then use the --theme option, or use raml2html as a library (not a command line tool). Check https://github.com/raml2html/raml2html/blob/master/examples/script.js for examples.
